services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ads_dental_db'
      - 'MYSQL_PASSWORD=LetMeIn'
      - 'MYSQL_ROOT_PASSWORD=Admin'
      - 'MYSQL_USER=root'
    ports:
      - '3307:3306'
  app:
    image: kchemutai/dockerspringdemo
    ports:
      - '8086:8081'
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/test
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: LetMeIn
    depends_on:
      - mysql
    networks:
      - default
    restart: always
