services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=AdsDentalDB'
      - 'MYSQL_PASSWORD=LetMeIn'
      - 'MYSQL_ROOT_PASSWORD=Adm1n@R00t'
      - 'MYSQL_USER=admin'
    ports:
      - '3305:3306'

  app:
    image: kchemutai/adsdentalsurgeries
    ports:
      - '8082:8081'
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/AdsDentalDB
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: admin
      spring.datasource.password: LetMeIn
    depends_on:
      - mysql
    networks:
      - default
    restart: always
#volumes:
#  todo-mysql-data: